# Generated by Django 4.2.3 on 2023-07-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctors_drug_stor_prescribe_request_patient_history_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nurse',
            new_name='Nurses',
        ),
    ]
